### ISSUE TITLE
2.8.0 is about SSL

### ISSUE THREAD

**Issue by sivar2311** [khoih-prog/SinricPro_Generic#3]
Hi Khoi!

Version 2.8.0 is about SSL (enabled by default now)
Did you noticed this?

Best regards
Boris

**Comment by khoih-prog** [comment]
Yes, but it's not working yet for other boards using Ethernet, WiFi, etc. if users don't use the correct libraries supporting SSL. Currently for only ESP32. ESP8266 still has some debug to do.

I think it's better to leave SSL as optional for this library, as you can see in :

1. [Light_FastLED_WS2812](https://github.com/khoih-prog/SinricPro_Generic/blob/master/examples/ESP/Light/Light_FastLED_WS2812/Light_FastLED_WS2812.ino)
2. [RGB_LED_Stripe_5050](https://github.com/khoih-prog/SinricPro_Generic/blob/master/examples/ESP/Light/RGB_LED_Stripe_5050/RGB_LED_Stripe_5050.ino)

Just add a definition to the sketch to enable SSL

```
#define WEBSOCKET_SSL       true
```

Best Regards,

KH

**Comment by sivar2311** [comment]
Yeah, must be hard to support SSL for many different boards.

SSL is still optional, but i changed the way around in  [SinricProConfig.h](https://github.com/sinricpro/esp8266-esp32-sdk/blob/26df87c1609dadc4a1a7cb6ec0b18f08116b28e0/src/SinricProConfig.h#L33).
To disable SSL you need to define `SINRICPRO_NOSSL` before including `SinricPro.h`

I think someday we will only allow SSL connections  - for security

**Comment by khoih-prog** [comment]
Actually, your current default way isn't working. You can check by adding warning as

```
#ifdef WEBSOCKET_SSL
  #warning Using WEBSOCKET_SSL
  // To get this working, WebSocketsClient.h needs to be fixed. See https://github.com/Links2004/arduinoWebSockets/issues/492
  webSocket.beginSSL(server.c_str(), SINRICPRO_SERVER_SSL_PORT, "/");
#else
  webSocket.begin(server.c_str(), SINRICPRO_SERVER_PORT, "/"); // server address, port and URL
#endif
``` 
---

I'm closing to enable SSL for all Ethernet libraries, as you can check 

1. [EthernetWebServer_SSL](https://github.com/khoih-prog/EthernetWebServer_SSL)
2. [EthernetWebServer_SSL_STM32](https://github.com/khoih-prog/EthernetWebServer_SSL_STM32)

but the users' habits will be changed slowly, unless you force them to do, such as allowing only SSL.

**Comment by sivar2311** [comment]
Yes, I forgot to remove the comment. I have made up for this recently. 
The original error has been fixed in the meantime. We have done extensive testing yesterday. 

Edit
This is the current Version of SinricProWebsocket.h - see line [122](https://github.com/sinricpro/esp8266-esp32-sdk/blob/26df87c1609dadc4a1a7cb6ec0b18f08116b28e0/src/SinricProWebsocket.h#L122) (comment removed)

**Comment by khoih-prog** [comment]
Not only the comment. The SSL is not working and webSocket.beginSSL() is never called.
I put the #warning to show you that it's not using SSL, no matter what you do currently.

**Comment by khoih-prog** [comment]
I have to do like this

```
// Currently working only on ESP32
#if (defined(WEBSOCKET_SSL) && WEBSOCKET_SSL)
  #warning Using WEBSOCKET_SSL
  SRP_LOGINFO1("Websocket: Connecting SSL to WebSocket Server: ", server);
#else
  #warning Not using WEBSOCKET_SSL
  SRP_LOGINFO1("Websocket: Connecting to WebSocket Server: ", server);
#endif
...

#if (defined(WEBSOCKET_SSL) && WEBSOCKET_SSL)
  // To get this working, WebSocketsClient.h needs to be fixed. See https://github.com/Links2004/arduinoWebSockets/issues/492
  webSocket.beginSSL(server, SINRICPRO_SERVER_SSL_PORT, "/");
#else
  webSocket.begin(server, SINRICPRO_SERVER_PORT, "/"); // server address, port and URL
#endif
```

and user has to define in sketch

```
#define WEBSOCKET_SSL      true
```

For ESP8266, you'll get the following compile error

```


In file included from /home/kh/Arduino/libraries/SinricPro/src/SinricPro.h:13:0,
                 from /home/kh/Arduino/khoih-prog_working/Testing_Libs/SinricPro_2.8.0/examples/Blinds/Blinds.ino:34:
/home/kh/Arduino/libraries/SinricPro/src/SinricProWebsocket.h: In member function 'void websocketListener::begin(String, String, String, SinricProQueue_t*)':
/home/kh/Arduino/libraries/SinricPro/src/SinricProWebsocket.h:124:60: error: no matching function for call to 'AdvWebSocketsClient::beginSSL(String&, int, const char [2])'
   webSocket.beginSSL(server, SINRICPRO_SERVER_SSL_PORT, "/");
                                                            ^
/home/kh/Arduino/libraries/SinricPro/src/SinricProWebsocket.h:124:60: note: candidate is:
In file included from /home/kh/Arduino/libraries/SinricPro/src/SinricProWebsocket.h:19:0,
                 from /home/kh/Arduino/libraries/SinricPro/src/SinricPro.h:13,
                 from /home/kh/Arduino/khoih-prog_working/Testing_Libs/SinricPro_2.8.0/examples/Blinds/Blinds.ino:34:
/home/kh/Arduino/libraries/WebSockets-2.3.1/src/WebSocketsClient.h:50:10: note: void WebSocketsClient::beginSSL(const char*, uint16_t, const char*, const uint8_t*, const char*)
     void beginSSL(const char * host, uint16_t port, const char * url = "/", const uint8_t * fingerprint = NULL, const char * protocol = "arduino");
          ^
/home/kh/Arduino/libraries/WebSockets-2.3.1/src/WebSocketsClient.h:50:10: note:   no known conversion for argument 1 from 'String' to 'const char*'
Multiple libraries were found for "Hash.h"
 Used: /home/kh/Downloads/Arduino/arduino-1.8.13/hardware/esp8266com/esp8266/libraries/Hash
 Not used: /home/kh/Arduino/libraries/STM32AsyncWebServer-master
Multiple libraries were found for "SinricPro.h"
 Used: /home/kh/Arduino/libraries/SinricPro
 Not used: /home/kh/Arduino/libraries/SinricPro_2.8.0
 Not used: /home/kh/Arduino/libraries/SinricPro_Generic-2.8.0
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

```

**Comment by sivar2311** [comment]
It is compiling and it is working:
```
[WS-Client] connect wss...
[WS-Client] connected to ws.sinric.pro:443.
[WS-Client][sendHeader] sending header...
[WS-Client][sendHeader] handshake GET / HTTP/1.1
Host: ws.sinric.pro:443

```
But you need to fix the lines:
`webSocket.beginSSL(server, SINRICPRO_SERVER_SSL_PORT, "/")`
is now
`webSocket.beginSSL(server.c_str(), SINRICPRO_SERVER_SSL_PORT, "/")`
(beginSSL needs a `char*`, not `String`) 
see [here](https://github.com/sinricpro/esp8266-esp32-sdk/blob/26df87c1609dadc4a1a7cb6ec0b18f08116b28e0/src/SinricProWebsocket.h#L123)

**Comment by khoih-prog** [comment]
OK, sorry I haven't got time to see that. Will fix now.

**Comment by sivar2311** [comment]
Yeah, i ran into this yesterday. 
I changed  the nonSSL Version (`webSocket.begin()`) to use `char*`, too

**Comment by sivar2311** [comment]
I made SSL as "OPT-OUT" if  `SINRICPRO_NOSSL`  is defined (see [SinricProConfig.h](https://github.com/sinricpro/esp8266-esp32-sdk/blob/26df87c1609dadc4a1a7cb6ec0b18f08116b28e0/src/SinricProConfig.h#L33))
I suggest to use this define for every board that does not support SSL

**Comment by khoih-prog** [comment]
Because the majority of the not-ESP boards using Ethernet, WiFi, etc. without SSL support, I think I just use the `OPT-IN` for this library now. 
I'll change to `OPT-OUT` when more boards have transparent SSL support, which I've been working on for a while. It's time-consuming and will take some more time as it depends on many more factors and libraries.

Best Regards,

KH

**Comment by khoih-prog** [comment]
Just added **Arduino SAMD21 Nano-33-IoT using WiFiNINA** to the SSL supporting list.

```
Starting SAMD_WiFiNINA_Light on SAMD_NANO_33_IOT
Version : SinricPro_Generic (v2.8.0)
Setup color temperature lookup table
colorTemperatureIndex[2200] = 0
colorTemperatureIndex[2700] = 1
colorTemperatureIndex[4000] = 2
colorTemperatureIndex[5500] = 3
colorTemperatureIndex[7000] = 4

[Wifi]: Connecting[WiFi]: IP-Address is 192.168.2.98
[SRP] DeviceId_Bin_t::fromString. DeviceId = 5ecxxxxxxxxxxxxxxxxxxxxx
[SRP] Creating new device. No current DeviceId = [SRP] DeviceId_Bin_t::toString. DeviceId = 5ecxxxxxxxxxxxxxxxxxxxxx
5ecxxxxxxxxxxxxxxxxxxxxx
[SRP] add(): Adding DeviceId = [SRP] DeviceId_Bin_t::toString. DeviceId = 5ecxxxxxxxxxxxxxxxxxxxxx
5ecxxxxxxxxxxxxxxxxxxxxx
[SRP] AppKey_Bin_t::fromString. AppKey = 51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[SRP] AppSecret_Bin_t::fromString. AppSecret = b29c6xxxxxxxxxxxxxxx
[SRP] begin(): App-Key = [SRP] AppKey_Bin_t::toString. AppKey = 51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[SRP] begin(): App-Secret = [SRP] AppSecret_Bin_t::toString. AppSecret = b29c6xxxxxxxxxxxxxxx
b29c6xxxxxxxxxxxxxxx
[SRP] DeviceId_Bin_t::toString. DeviceId = 5ecxxxxxxxxxxxxxxxxxxxxx
[SRP] AppKey_Bin_t::toString. AppKey = 51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
[SRP] Websocket: Connecting SSL to WebSocket Server:  ws.sinric.pro
Websocket: headers:
appkey:51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
deviceids:5ecxxxxxxxxxxxxxxxxxxxxx
restoredevicestates:false
ip:192.168.2.98
mac:74:7A:C9:AE:11:4C
platform:SAMD_NANO_33_IOT
version:2.8.0
[WS] [WS-Client] Connect wss...
[WS] [WS-Client] new WEBSOCKETS_NETWORK_SSL_CLASS
[WS] [WS-Client] After new WEBSOCKETS_NETWORK_SSL_CLASS
[WS] [WS-Client] connectedCb
[WS] [WS-Client][connectedCb] Connected to Host: ws.sinric.pro , Port: 443
[WS] [WS-Client] [sendHeader] Sending header...
[WS] [WS-Client] [sendHeader] Handshake: GET / HTTP/1.1
Host: ws.sinric.pro:443
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: CBN6MQWQWXTdIq8djs1qrw==
Sec-WebSocket-Protocol: arduino
appkey:51c2xxxxxxxxxxxxxxxxxxxxxxxxxxxx
deviceids:5ecxxxxxxxxxxxxxxxxxxxxx
restoredevicestates:false
ip:192.168.2.98
mac:74:7A:C9:AE:11:4C
platform:SAMD_NANO_33_IOT
version:2.8.0
User-Agent: arduino-WebSocket-Client
```

Still have a very long list to go.

**Comment by sivar2311** [comment]
Yeayy! Another device "secured" 👍 
Good work!
