### ISSUE TITLE
Thermostat no longer responding to Alexa, but it does respond on the portal.

### ISSUE THREAD

**Issue by PopcornAWH** [khoih-prog/SinricPro_Generic#5]
Today my thermostat (Modbus sketch on MKR WiFi 1010) no longer responds to voice commands from Alexa,
The Sinric.pro portal works just fine, all commands and events fully functional.
Alexa does get the room temperature updates from the device, but can't give commands, it says it's having network issues.
Any hints where to look for the issue?

**Comment by khoih-prog** [comment]
Thanks for using the library.

I really have no idea what's happening there, as there are numerous factors affecting the operation.
I just can only suggest to try steps-by-steps to isolate the issue

1. Reset / Power ON/OFF
2. Login to [**Sinric.pro**](https://sinric.pro/) and try to control manually from there
3. Control directly from Alexa app on Cell phone
4. Try on other boards and/or equipments controlled by Sinric.pro
5. Try other Alexa-controlled commercial devices to see if Alexa is OK there.
6. Change the SinricPro ID
7. Post / search for similar issues on [SinricPro SDK](https://github.com/sinricpro/esp8266-esp32-sdk/issues) or [**Sinric.pro**](https://sinric.pro/)

---

@kakopappa, @sivar2311

Do you know there is any current issue with Alexa & Sinric.pro?

**Comment by kakopappa** [comment]
Hi @PopcornAWH 

Yesterday we released a new version to production which might have disconnected your device. If portal to device connection works fine, try re-linking the Alexa Skill.

**Comment by kakopappa** [comment]
@PopcornAWH  We managed to reproduce this issue and fix it. can you please check now?

**Comment by PopcornAWH** [comment]
Yes! Fully functional on voice-commands again, great work! Thanks a lot!
Now I can be lazy again, and use the voice commands to set my thermostat.
