### ISSUE TITLE
CAMERA_MODEL_AI_THINKER is listed in Camera, but not in select_pins.h

### ISSUE THREAD

**Issue by khoih-prog** [khoih-prog/SinricPro_Generic#6]
From @luigiamadei at https://github.com/khoih-prog/SinricPro_Generic/commit/f13418ca368596c59174507431a88a0128953fb2#r60522532

**Comment by khoih-prog** [comment]
Just updated [**Camera**](https://github.com/khoih-prog/SinricPro_Generic/tree/master/examples/ESP/Camera) to add many more models, including `CAMERA_MODEL_AI_THINKER`

**Comment by luigiamadei** [comment]
Thank you for your attention.
